name: Automatic Deployment Process

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step-1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step-2: Setup SSH Key
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_KEY }}

      # Step-3: Add EC2 to Known Hosts
      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 44.194.64.5 >> ~/.ssh/known_hosts

      # Step-4: SSH into EC2 & Deploy Code
      - name: Deploy Code to the Server
        uses: appleboy/ssh-action@master
        with:
          host: 44.194.64.5
          username: ubuntu
          key: ${{ secrets.PEM_KEY }}
          port: 22
          script: |
            cd /var/www/html/brewnique

            # Stash any local changes
            git stash -u

            # Pull the latest code from GitHub
            git pull origin main

            # Install dependencies without packages
            #composer install

            # Run migrations if necessary
            php artisan migrate

            # Re-apply the stash changes
            git stash pop

            # Clear caches and optimize application
            php artisan optimize:clear


            echo "......Deployment completed......"
